---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends \
            shfmt
      - name: Check for tabs in shell scripts
        run: |
          ! grep -P "^\t" --line-number *.sh
      - name: Run ShellCheck
        run: |
          find . -name \*.sh -type f -exec shellcheck {} +
      - name: Run shfmt
        run: |
          find . -name \*.sh -type f -exec shfmt -d -i 4 {} +
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - linter
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create default.env file
        run: cp default.env.example default.env
      - name: Build images
        run: |
          for script in ./*/build.sh ; do
              "$script"
          done
