---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends \
            shfmt
      - name: Check for tabs in shell scripts
        run: |
          ! grep -P "^\t" --line-number *.sh
      - name: Run ShellCheck
        run: |
          find . -name \*.sh -type f -exec shellcheck {} +
      - name: Run shfmt
        run: |
          find . -name \*.sh -type f -exec shfmt -d -i 4 {} +

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    needs:
      - linter
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8  # v4.2.0
        with:
          platforms: arm64
      - name: Create default.env file
        run: cp default.env.example default.env
      - name: Build images
        run: |
          for script in ./*/build.sh ; do
              "$script"
          done
